# Generated by Django 5.2.11 on 2026-03-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_by',
            new_name='created',
        ),
    ]
