# Generated by Django 5.2.11 on 2026-03-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_created_by_task_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='created_by',
        ),
    ]
